/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/bubbles.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.001']} position={[0, 0.1, 0.01]} />
      <mesh
        geometry={nodes.Sphere001.geometry}
        material={nodes.Sphere001.material}
        position={[-0.8, 0.54, 0.86]}
        scale={[0.15, 0.15, 0.15]}
      />
      <mesh
        geometry={nodes.Sphere003.geometry}
        material={materials.Material}
        position={[0.7, 0.55, 0.92]}
        scale={[0.15, 0.15, 0.15]}
      />
    </group>
  )
}

useGLTF.preload('/bubbles.glb')
