/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/cupcake.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder.geometry} material={materials['Material.001']} position={[0, 0.62, 0]} />
      <mesh
        geometry={nodes.Torus.geometry}
        material={materials['Material.004']}
        position={[0, 1.21, 0]}
        scale={[0.74, 0.74, 0.74]}
      />
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={materials['Material.005']}
        position={[6.05, 0.17, 0]}
        rotation={[0, 0, -2.18]}
        scale={[0.04, 0.09, 0.04]}
      />
      <mesh
        geometry={nodes.Cylinder002.geometry}
        material={materials['Material.006']}
        position={[6.39, 0.27, 0]}
        scale={[0.04, 0.09, 0.04]}
      />
      <mesh
        geometry={nodes.Cylinder003.geometry}
        material={nodes.Cylinder003.material}
        position={[6.6, -0.01, 0]}
        scale={[0.03, 0.08, 0.03]}
      />
      <mesh
        geometry={nodes.Cylinder004.geometry}
        material={nodes.Cylinder004.material}
        position={[5.82, 0, 0]}
        scale={[0.03, 0.08, 0.03]}
      />
      <mesh
        geometry={nodes.Plane.geometry}
        material={nodes.Plane.material}
        position={[0, 0.05, 0]}
        scale={[14.4, 14.4, 14.4]}
      />
      <mesh
        geometry={nodes.Torus012.geometry}
        material={materials['Material.007']}
        position={[-0.39, 1.04, 1.07]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.3, 0.26, 0.3]}
      />
      <mesh
        geometry={nodes.Torus001.geometry}
        material={materials['Material.008']}
        position={[0.55, 1.05, 1.06]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.3, 0.26, 0.3]}
      />
    </group>
  )
}

useGLTF.preload('/cupcake.glb')
