/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Ring1.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={materials['Material.002']}
        position={[-0.09, 0, -0.01]}
        rotation={[2.91, 0, 0]}
        scale={[0.01, 0, 0.01]}
      />
    </group>
  )
}

useGLTF.preload('/Ring1.glb')
